version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/database_name
    volumes:
      - ./config.py:/app/config.py

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_name
